### ISSUE TITLE
What am I missing? 

### ISSUE THREAD

**Issue by HongSeokHwan** [aadsm/jsmediatags#1]
Hi, This is really awesome project. I am so happy to see this library.
But, unfortunately I can not use 'Browser version'
I always got an error msg like 'No suitable tag reader found.'
I believe I select correct mp4 files.
Here is my codepen,

http://codepen.io/HongSeokHwan/pen/QyqWqa

What am I missing? Is it work in your computer?

**Comment by aadsm** [comment]
Works well here, could be an issue with the file you're using. Let me provide more hooks into debugging, this is something I wanted to do for a while now.

**Comment by HongSeokHwan** [comment]
Thank you for your quick answer.
I tried more than 10 mp4 files and all of my files are failed.

I attached one of my bad video files. Is it possible to check it in you
environment?

And if it is possible, Can you give me that good mp4 file that you used?
I really want to check your code using your good file. :)

Thank you for your great code.

from Hong


2016-01-15 16:20 GMT+09:00 António Afonso <notifications@github.com>:

**Comment by aadsm** [comment]
I don't think you can attach files to github issues like that. If you are on a unix machine can you run `file music.mp4` and post the result?

**Comment by HongSeokHwan** [comment]
I couldn't find 'music.mp4' in my linux server. 
So, I post bad mp4 file in my temp web server, and I believe you can see this file.

http://dev.qoontree.com:8765/sample-video.mp4

I also check the file(sample-video.mp4) using exiftool and this is the result.

http://dev.qoontree.com:8765/metadata.txt

Can you check it for me?

**Comment by aadsm** [comment]
`music.mp4` was just an example,  for your case it would have been `sample-video.mp4`, but what you provided is even better.

I see the problem, the MP4TagReader is explicitly requiring the 'ftyp' to be `M4A` while this file is `isom`, this is why it doesn't recognize it. There is no reason to only read `M4A` types so let me fix that.

Thanks for finding and reporting it!

PS: You can find more information about 'ftyp' here: http://www.ftyps.com/

**Comment by HongSeokHwan** [comment]
Great! I am looking forward to new patch. Thank you very much.
