### ISSUE TITLE
Remote file loading fail.

### ISSUE THREAD

**Issue by alexmatveev** [aadsm/jsmediatags#11]
Remote host file loading doesn't work, even from example code.
See screenshot below:
![2016-03-14 16-48-40](https://cloud.githubusercontent.com/assets/1456669/13746583/1cae3718-ea05-11e5-9f98-26cab50c47c8.png)

Using with browser JS.

**Comment by aadsm** [comment]
You need to configure the server to allow cross-domain requests. This is not an issue with this library but it's related to the cross-domain policy that browsers implement.

You can learn more about it here https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS but basically you need to configure the server to present the `Access-Control-Allow-Origin` header.

**Comment by alexmatveev** [comment]
@aadsm You mean, to configure remote server, which serves mp3 file? There is no way to do this in my case :(

**Comment by aadsm** [comment]
Yeah, it's a security feature that browsers provide. You can use a CORS proxy like  https://crossorigin.me/ to get around this.
