### ISSUE TITLE
Bad performance in for loop?

### ISSUE THREAD

**Issue by CodeF0x** [aadsm/jsmediatags#111]
Hi!

I'm reading meta information of n files. The amount of those files varies gretly. I'm doing that in a for loop and this process blocks my entire application for ~ 1 to 2 seconds, depending on how many file there are.

I guess it's this library that causes this issue because when using dummy values instead of values gotten from the files, that heavy delay does not appear or is at least way smaller. (Using files without any meta information are also not affected of the delay).

I've implemented it like this:

```
listMusicFiles: function(files) {
    // Not important stuff here

    for (let i = 0; i < files.length; i++) {
      const container = document.createElement('div');
      container.setAttribute('data-file-path', files[i].path);
      container.addEventListener('click', function() {
        play(this.getAttribute('data-file-path'));
      });

      const name = document.createElement('div');
      const album = document.createElement('div');
      const artist = document.createElement('div');

      new media.Reader(files[i].path)
        .setTagsToRead(['title', 'album', 'artist'])
        .read({
          onSuccess: tag => {
            let songNameSplitted = files[i].path.split('/');
            songNameSplitted = songNameSplitted[songNameSplitted.length - 1];

            name.innerText = tag.tags.title ? tag.tags.title : songNameSplitted;
            album.innerText = tag.tags.album ? tag.tags.album : 'Unknown';
            artist.innerText = tag.tags.artist ? tag.tags.artist : 'Unknown';
          },
          onError: err => console.error(err)
        });

      container.appendChild(name);
      container.appendChild(album);
      container.appendChild(artist);
      list.appendChild(container);
    }
  }
```

Is there something I can do about this? Or is it the fact that I create that many DOM elements at once?

Thanks,
Tobi "CodeF0x"

PS. Thanks for this great library! It makes things so much easier!

**Comment by CodeF0x** [comment]
Thanks for your fast reply and your help. I really appreciate it! 

I tried as you suggested with DocumentFragment, but that unfortunately helped just a little. I maybe should clarify my problem. The process is not blocked in a way that nothing happens and suddenly there's a list of 300 elements. It's more "blocked" in a way that you can see the creation of the elements "lagging". I'll attach a GIF for better understanding.

![lagging](https://user-images.githubusercontent.com/33719652/55882919-9b046a00-5ba5-11e9-874f-49bff14e3358.gif)

**Comment by CodeF0x** [comment]
After almost two months of some testing and researching, I came to the conclusion that it must be a problem with Electron, and not with this library, as I couldn't replicate the issue in any browser on any operating system. 

Thanks anyway for your help!

**Comment by aadsm** [comment]
Oh interesting, I was actually not expecting this. Thank you for the update.
