### ISSUE TITLE
Cannot load lib on node.js

### ISSUE THREAD

**Issue by xandros15** [aadsm/jsmediatags#115]
After install new version, by command `npm install jsmediatags --save` after run app by `node app.js` got error `Error: Cannot find module 'jsmediatags'`. Older versions doesn't work too. 

Runkit on npm got error too:
![image](https://user-images.githubusercontent.com/10834079/60400470-5c62c800-9b74-11e9-85dd-516e7b629357.png)

**Comment by aadsm** [comment]
Thanks for the report and sorry about this, I’ve just fixed it and also created a little script to prevent this from happening in the future again.
