### ISSUE TITLE
URL.createObjectURL(file)

### ISSUE THREAD

**Issue by strukturart** [aadsm/jsmediatags#118]
Hello,
I is possible to use [URL.createObjectURL(file)](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) to read out the metadata ?

**Error message:**
`Error: No suitable file reader found for blob:app://{9d3f6e1c-7dd9-4875-9b12-19f78a862775}/8a4deaa3-afbf-4f42-8d38-d5010022fce6`

**Code snippet**
```
cursor.onsuccess = function () {
		if(cursor.result) 
		{
			var file = cursor.result;

			if(file.type.match('audio/*'))
			{

				fileURL = URL.createObjectURL(file)


				if(jsmediatags)
				{

				jsmediatags.read(fileURL, {
					onSuccess: function(tag) {
					console(tag);
				},
					onError: function(error) {
					console(':(', error.type, error.info);
					}
				});

				}
```

**Comment by Borewit** [comment]
I am not sure if I understand exactly what you want. I assume you want to read from a [File](https://developer.mozilla.org/en-US/docs/Web/API/File) (which is also a [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob))

[music-metadata-browser](https://github.com/Borewit/music-metadata-browser) can read the Blob/file
using [parseBlob](https://github.com/Borewit/music-metadata-browser#parsereadablestream-function):

```js
const musicMetadata = require('music-metadata-browser');

// No need for: fileURL = URL.createObjectURL(file)

musicMetadata.parseBlob(file).then(metadata => {
  // do something with the metadata
});
```

Demo: https://audio-tag-analyzer.netlify.com/

**Comment by strukturart** [comment]
I had writen an musicplayer app for the nokia8110(KaiOS)
https://github.com/strukturart/audio
It works but the filenames are not nice to read(12092019_podcast.mp3), so I wanted to read the metatags.
Do you think I should do it with music-metadata-browser  ?

**Comment by Borewit** [comment]
I have no experience with Nokia apps. [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) is designed for module based browser application. It's very complete, very robust, but larger then [jsmediatags](https://github.com/aadsm/jsmediatags). With [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) you need something like webpack, [jsmediatags](https://github.com/aadsm/jsmediatags) has pre-cooked all in one distribution for the browser.

**Comment by strukturart** [comment]
Thank you it works with music-metadata-browser.

**Comment by Borewit** [comment]
Note that the [musicmetadata.js](https://github.com/strukturart/audio/blob/master/application/assets/js/musicmetadata.js) you copied into your project is not the same as [music-metadata-browser](https://github.com/Borewit/music-metadata-browser). Although it has common roots, it is a predecessor module of years back. That one included this pre-bundled just like jsmediatags. If your project grows larger you want to use module bundler, which basically enables you to manage your dependencies via npm, and build your own distribution with everything you need. One of the many benefits is that it prevent duplicate dependencies.
