### ISSUE TITLE
No sync method?

### ISSUE THREAD

**Issue by venomlust** [aadsm/jsmediatags#12]
There's no syncRead? I'm trying to use anothers plugins to sync but that onSuccess is giving me trouble. Any solution or another plugin like jsmediatags?

**Comment by aadsm** [comment]
The read has to be sync, otherwise it would completely block the browser or nodejs.
What kind of troubles do you have?

**Comment by venomlust** [comment]
WhatI was trying to do is somthing like this:

```
var obj = null;
jsmediatags.read(path, {
  onSuccess: function(tag) {
    obj = tag;
    console.log(tag);
  },
  onError: function(error) {
    console.log(':(', error.type, error.info);
  }
});
return obj;
```
Its returning null and then printing tag what I need is something like this:

```
var obj =null;
obj = jsmediatags.readSync(path);
retun obj;
```

by the way i have some trouble with this music [Realms Of Fear.mp3](http://www.mediafire.com/download/2qygoe4pdtqgnhn/03+Realms+of+Fear.mp3)
some kind of offset error (sorry i dont have pics from the error right now)

**Comment by aadsm** [comment]
Is it the same as #14 ?

**Comment by venomlust** [comment]
Yeah same, the only difference is the offset number

**Comment by aadsm** [comment]
Oops, I meant the read has to be async yes.
I'm not quite sure how it can be useful, I feel strongly against implementing it unless there's a very good reason.

**Comment by grazinskis** [comment]
Hi,
being that the reading is in an async method, am I correct to think that there is no way to catch and handle an exception coming from it? And if I am correct, wouldn't it be better to fall back to the onError callback in such a case?
Personally, I was having problems with the "offset" exception, but it seems like your last commit (3.2.2) has fixed it.

**Comment by venomlust** [comment]
It's useful because most of file reads are made asynchronous and reading it again with async methods may cause callback hell. It shorten code lines for some people like me, insted coding 10 lines i could code 2.
For sure this project is yours but I think its cool to do something that another dont have (yes i've been searching and didin't find any another media tag reader with sync methods).

**Comment by aadsm** [comment]
@grazinskis brings a really good point on the lack of proper error handling. I was originally planning to use promises, which solves this issue. However, support in the browser was lacking at the time and I didn't want to include a huge library. This wasn't an issue in the past so it wouldn't bring much value.
Today most browsers implement it and there are <500b Promises/A+ implementations so I want to rethink this approach.

@venomlust I don't think the use of promises would solve your problem though. This introduces a change from `jsmediatags.read(url, {onSuccess: handleTags})` to `jsmediatags.read(url).then(handleTags)`.
However, with the introduction of generators in ES6, or even better, the `async/await` operators in ES7 you can code with promises in a sync way: `tags = await jsmediatags.read(url);`.

I hope this clarifies my position on this topic.

**Comment by aadsm** [comment]
@venomlust I'm not able to replicate the issue with the file you gave, can you try again? It might have been fixed in the meanwhile.

**Comment by krish512** [comment]
Hi,
I tried doing `tags = await jsmediatags.read(url);` but it doesn't seem to work.

Is that supported with current release? What changes do I need to make to get this working?
Please share a code sample if possible, need this urgently.

**Comment by jeghers** [comment]
In nodejs, I need to parse tags out of many many many files, and if they are done async, then too many are done at once causing "too many open file" errors.

I really need to do one at a time sequentially.  It's not in a browser so blocking doesn't matter.  I'll have to go into callback hell now because no sync support exists.

The lack of sync support is killing me.
