### ISSUE TITLE
Only get 'shortcut' tags from MP4, nothing more

### ISSUE THREAD

**Issue by R-E-Tired** [aadsm/jsmediatags#129]
When I try to get all the tags from a MP4 file using:

`jsmediatags.read("filename.mp4", {
  onSuccess: function(tag) {
    var tags = tag.tags;
  }
});`

then I only get the so-called shortcut tags, but nothing more.
Same is true when I try to get specific tags.
Using e.g. MediaInfo or VLC Media Player, I see that the tags are available and have data.

When retrieving tags from MP3, all is OK, but not from MP4 !

I already say Thanks for a working solution !

**Comment by aadsm** [comment]
Can you give me a repro? I've actually haven't tested much with mp4, but only with m4a, although they should use the same container type, but not sure if the same tags though.

**Comment by R-E-Tired** [comment]
Thanks for trying to solve this.
Please download www.wijchman.com/test4tags.mp4
Both VLC media player as well as MediaInfo see the tags I'm interested in.
MediaInfo output:

Complete name                            : D:\WEB\test4tags.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42)
File size                                : 10.1 MiB
Duration                                 : 6 s 740 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 12.6 Mb/s
Encoded date                             : UTC 2020-04-03 11:35:04
Tagged date                              : UTC 2020-04-03 11:35:04
sonm                                     : Born to Run
soco                                     : Saskia
soar                                     : Bruce Springsteen

The last 3 entries, sonm (sorted name of title), soco (sorted name of composer, and here I mean the composer of the video) and soar (sorted name of artist) are the tags I'm interested in, but being able to read all available tags would of course make your code even more useful.
Thanks again !
