### ISSUE TITLE
How to retrieve image from a MP3 File?

### ISSUE THREAD

**Issue by remcova** [aadsm/jsmediatags#13]
I tried to get the image from a MP3 file with this code but it doesn't work, I get this error message in Console: "No suitable file reader found for" jsmediatags.min.js:64

Does anybody know how to get the image correctly from a MP3 file? I searched a lot on Google but couldn't find any examples for jsmediatags.

    
   
	  
		jsmediatags.read("test.mp3", {
		    onSuccess: function(tag) {
			  var tags = tag.tags;
			  console.log(tags);
			  
			  var image = tags.picture;
			  if (image) {
				var base64String = "";
				for (var i = 0; i < image.data.length; i++) {
					base64String += String.fromCharCode(image.data[i]);
				}
				var base64 = "data:" + image.format + ";base64," +
						window.btoa(base64String);
				document.getElementById('picture').setAttribute('src',base64);
			  } else {
				document.getElementById('picture').style.display = "none";
			  }
			  
			}
		});

**Comment by remcova** [comment]
I fixed it!

**Comment by zhirzh** [comment]
How exactly did you fix it?
Please post the changes you made.

**Comment by remcova** [comment]
Here is how I fixed it for my app:
`var image = tags.picture;

                                if (image) {
                                    var base64String = "", cover_filename;
                                    i = 0;
                                    while (i < image.data.length) {
                                        base64String += String.fromCharCode(image.data[i]);
                                        i++;
                                    }

                                    i = 0;
                                    while (i < valid_extensions.length) {
                                        if (image.format.indexOf(valid_extensions[i]) >= 0) {
                                            cover_filename = id + "." + valid_extensions[i];
                                        }
                                        i++;
                                    }
                                }

                                $.ajax({
                                    type: "POST",
                                    url: hostURL + "server/index.php",
                                    data: {
                                        action: 'insertsong',
                                        name: tags.title,
                                        artist: tags.artist,
                                        url: fileURL,
                                        cover_base64: ( image ? encodeURIComponent(window.btoa(base64String)) : "" ),
                                        covername: ( image ? cover_filename : "-1" )
                                    }
                                }).done(function (data) {

                                }).fail(function (data) {
                                });`

**Comment by mrieck** [comment]
No need to send it to server, just make sure it's using a valid mime type instead of what's in the "format" variable.   "image/jpeg" instead of "JPG"

`    jsmediatags.read("test.mp3", {
        onSuccess: function(tag) {
          var tags = tag.tags;
          console.log(tags);

          var image = tags.picture;
          if (image) {
            var base64String = "";
            for (var i = 0; i < image.data.length; i++) {
                base64String += String.fromCharCode(image.data[i]);
            }
            var base64 = "data:image/jpeg;base64," +
                    window.btoa(base64String);
            document.getElementById('picture').setAttribute('src',base64);
          } else {
            document.getElementById('picture').style.display = "none";
          }

        }
    });
`

**Comment by maicss** [comment]
How about use `<img src="blog: xxxx">`

```
input.onchange = function (e) {
      jsmediatags.read(e.target.files[0], {
        onSuccess: function(tagObj) {
          const tags = tagObj.tags
          console.log(tagObj)
          const img = document.createElement('img')
          img.src = URL.createObjectURL(new Blob(tags.picture.data, {type: tags.picture.format}))
          img.onload = function(e) {
            URL.revokeObjectURL(img.src);
          };
          input.parentNode.appendChild(img)

        },
        onError: function(error) {
          console.log(error);
        }
      })
    }
```

not work...

**Comment by loilo** [comment]
An alternative approach using Blobs:

```js
jsmediatags.read("test.mp3", {
  onSuccess: function(tag) {
    var tags = tag.tags;

    var image = tags.picture;
    if (image) {
      var blob = new Blob(new Uint8Array(image.data), { type: image.format });
      var url = URL.createObjectURL(blob);
      document.getElementById('picture').setAttribute('src', url);
    } else {
      document.getElementById('picture').style.display = "none";
    }
  }
});
```
