### ISSUE TITLE
tags'title is gibberish character

### ISSUE THREAD

**Issue by jonahzheng** [aadsm/jsmediatags#134]
source code

`var jsmediatags = require("jsmediatags");

new jsmediatags.Reader("https://api.zanmeishi.com/song/p/27090.mp3")
	//.setTagsToRead(["title", "artist"])
	.read({
		onSuccess: function (tag) {
			console.log(JSON.stringify(tag));
		},
		onError: function (error) {
			console.log(':(', error.type, error.info);
		}
	});`

result:
`{"type":"ID3","version":"2.3.0","major":3,"revision":0,"flags":{"unsynchronisation":false,"extended_header":false,"experimental_indicator":false,"footer_present":false},"size":81,"tags":{"title":"¹ú¶ÈÒÑ½µÁÙ","artist":"çÑÃ÷Æ½","album":"ÐÅÍû°®","genre":"Other","TPE1":{"id":"TPE1","size":7,"description":"Lead performer(s)/Soloist(s)","data":"çÑÃ÷Æ½"},"TALB":{"id":"TALB","size":7,"description":"Album/Movie/Show title","data":"ÐÅÍû°®"},"TCON":{"id":"TCON","size":6,"description":"Content type","data":"Other"},"TIT2":{"id":"TIT2","size":11,"description":"Title/songname/content description","data":"¹ú¶ÈÒÑ½µÁÙ"}}}`

thank you!

**Comment by Fallofleaf** [comment]
I have this problem ,too.Did you solve this problem?

**Comment by Fallofleaf** [comment]
It seems I have found a ssolution.
You can use Mp3tag software to change the track number to 1.
Probably because the track number is not specified,the encoding is GBK,which leads to garbled characters.

**Comment by jonahzheng** [comment]
@Fallofleaf thank you, but the MP3 file is on someone else's server and I can't change it.

I tried iconv-Lite to decode the output, and it turned out to be a gibberish.

**Comment by Borewit** [comment]
The issue is indeed with [track](https://api.zanmeishi.com/song/p/27090.mp3), probably caused by a wrong encoding specification.

In other words, the title of the track is set to: `¹ú¶ÈÒÑ½µÁÙ`, which looks like [Mojibake](https://en.wikipedia.org/wiki/Mojibake). 

```js
const fetch = require('node-fetch');
const musicMetadata = require('music-metadata');

const url = 'https://api.zanmeishi.com/song/p/27090.mp3';

(async () => {
  const response = await fetch(url);
  const metadata = await musicMetadata.parseStream(response.body);
  console.log(metadata.common);
})();
```

```
{
  track: { no: null, of: null },
  disk: { no: null, of: null },
  artists: [ 'çÑÃ÷Æ½' ],
  artist: 'çÑÃ÷Æ½',
  album: 'ÐÅÍû°®',
  genre: [ 'Other' ],
  title: '¹ú¶ÈÒÑ½µÁÙ'
}
```

**Comment by jonahzheng** [comment]
@Borewit thank you, similar url, https://api.zanmeishi.com/song/p/22228.mp3, https://api.zanmeishi.com/song/p/39515.mp3,
I'm not sure, what code does it use. I tried iconv-Lite to decode the json output,but it is mojibake.

**Comment by Borewit** [comment]
Regarding the [first track](https://api.zanmeishi.com/song/p/27090.mp3), I think the original character encoding is [GB2312](https://en.wikipedia.org/wiki/GB_2312):

```js
const fetch = require('node-fetch');
const musicMetadata = require('music-metadata');

const iconv = require('iconv-lite');

const url = 'https://api.zanmeishi.com/song/p/27090.mp3';
(async () => {
  const response = await fetch(url);
  const metadata = await musicMetadata.parseStream(response.body);
  console.log(metadata.common);

  ['artist', 'title', 'album'].forEach(tag => {
    const mojibake = metadata.common[tag];
    console.log(`${tag}: ${iconv.decode(mojibake,'GB2312')}`);
  });
})();
```

```
artist: 缪明平
title: 国度已降临
album: 信望爱
```

**Comment by Borewit** [comment]
Or using [jsmediatags](https://github.com/aadsm/jsmediatags), same story:

```js
const jsmediatags = require('jsmediatags');
const iconv = require('iconv-lite');

function readMetadata(url) {
  return new Promise((resolve, reject) => {
    jsmediatags.read(url, {
      onSuccess: result => resolve(result),
      onError: error => reject(error)})
  });
}

const url = 'https://api.zanmeishi.com/song/p/27090.mp3';
(async () => {
  const metadata = await readMetadata(url);

  ['artist', 'title', 'album'].forEach(tag => {
    const mojibake = metadata.tags[tag];
    console.log(`${tag}: ${iconv.decode(mojibake,'GB2312')}`);
  });
})();
```

**Comment by jonahzheng** [comment]
@Borewit thank you very mush, you'er so cool.
