### ISSUE TITLE
Electron - DeprecationWarning: Buffer() is deprecated due to .....

### ISSUE THREAD

**Issue by RandomTomato** [aadsm/jsmediatags#144]
Hi there, This is my first time reporting an issue on GitHub so I am unsure if I am doing it correctly so hopefully what I write makes sense.

I am currently updating my application to the newest version of the Electron Framework and while doing some testing in my application, when I trigger an event to run your "read()" function it causes an error to occur in my console along the lines of the following.

<img src="https://i.imgur.com/xVyMNQu.png"/>

I have isolated the error to the read function as when I disable it, the error does not appear. Any idea to what it could be? or if it can be fixed??

Thank you so much in advanced! I appreciate it a lot!
~Brandon aka. RandomTomato

**Comment by danii1** [comment]
PR #160 fixes it.
