### ISSUE TITLE
Error: No suitable file reader found for

### ISSUE THREAD

**Issue by dersimn** [aadsm/jsmediatags#15]
I was testing your script for usage in a browser (tested on Safari, Chrome, Firefox).
The following HTML file should just show a button, you select a file from your local disk and it puts the ID3 Tags etc. in the JavaScript Console (just for testing so far).

Try it yourself: https://jsfiddle.net/d68kww4v/

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
		<script src="https://github.com/aadsm/jsmediatags/raw/master/dist/jsmediatags.js"></script>
		<script>
			$(function(){
				var jsmediatags = window.jsmediatags;

				$("#filesToUpload").change(function(e){
					//for every file...
					for (var i = 0; i < e.target.files.length; i++) {
						console.log('File ' + (i + 1) + ':  ' + e.target.files[i].name);
						jsmediatags.read(e.target.files[i].name, {
						  onSuccess: function(tag) {
						    console.log(tag);
						  },
						  onError: function(error) {
						    console.log(error);
						  }
						});
					}
				});
			});
		</script>
	</head>
	<body>
		<form>
			<input name="filesToUpload[]" id="filesToUpload" type="file" multiple>
		</form>
	</body>
</html>
```

However it always results in an error like:

```
Error: No suitable file reader found for 
_findFileReaderjsmediatags.js:2181
_getFileReaderjsmediatags.js:2169
readjsmediatags.js:2147
readjsmediatags.js:2116
(anonyme Funktion)jsmediatags.html:14
dispatchjquery-2.2.3.min.js:2:7542
handlejquery-2.2.3.min.js:2:5625
```

**Comment by ManarKamel** [comment]
I'm not the developer, but just change from e.target.files[i].name to e.target.files[i], it will work.

On the side note: Don't do for loop here, create custom loop function for the files, to prevent memory leak in JavaScript

**Comment by dersimn** [comment]
I tried different inputs, but it always results in an error. Without the `.name` it shows:

```
TypeError: e.data.slice is not a function. (In 'e.data.slice(0,d-e.offset)', 'e.data.slice' is undefined)
valuejsmediatags.min.js:6:234
onloadendjsmediatags.min.js:4
```

I actually got the idea to use the `.name` attribute by inspecting the code of the older JavaScript-ID3-Reader project from: http://web.ist.utl.pt/antonio.afonso/www.aadsm.net/libraries/id3/

**Comment by aadsm** [comment]
Thanks for reporting.
I should be able to look into this weekend.

On Thursday, April 21, 2016, Simon Christmann <notifications@github.com>
wrote:

> I tried different inputs, but it always results in an error. Without the
> .name it shows:
>
> TypeError: e.data.slice is not a function. (In 'e.data.slice(0,d-e.offset)', 'e.data.slice' is undefined)
> valuejsmediatags.min.js:6:234
> onloadendjsmediatags.min.js:4
>
> I actually got the idea to use the .name attribute by inspecting the code
> of the older JavaScript-ID3-Reader project from:
> http://web.ist.utl.pt/antonio.afonso/www.aadsm.net/libraries/id3/
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aadsm/jsmediatags/issues/15#issuecomment-212823028>
>


-- 
Best regards,
António Afonso

**Comment by aadsm** [comment]
The old library works with strings to identify the file, this one uses the actual file object.
I've updated your fiddle by removing the .name and using the CDNJS version of the library (the latest chrome doesn't run the github link because of its content type) and it works: https://jsfiddle.net/3n44gy1v/

Can you try again? Do you have this problem with any file?

@ManarKamel Where is the memory leak you mention?

**Comment by dersimn** [comment]
Thanks for looking into.
I tried several mp3 files and some m4a created by iTunes. With your new jsfiddle at least Firefox 45.0.2 works fine.

To test the other browsers, I updated your fiddle to use the non-minimalized version for better debugging: https://jsfiddle.net/3n44gy1v/1/

Chrome 39.0.2171.95 (64-bit) is throwing this error: 
```
Uncaught TypeError: undefined is not a function
addData jsmediatags.js:207
browserFileReader.onloadend jsmediatags.js:109
```

Safari 9.1 (11601.5.17.1) as well:
```
[Error] TypeError: firstChunk.data.slice is not a function. (In 'firstChunk.data.slice(0, offset - firstChunk.offset)', 'firstChunk.data.slice' is undefined)
	addData (jsmediatags.js:207)
	onloadend (jsmediatags.js:109)
```

**Comment by aadsm** [comment]
Thanks for the browser versions. That is a really old Chrome version btw, the latest is 50 :)
Safari and old versions of Chrome didn't implement `slice` in TypedArrays, will put a fix up soon.
