### ISSUE TITLE
Is this right library for getting creation date of mp4?

### ISSUE THREAD

**Issue by HongSeokHwan** [aadsm/jsmediatags#2]
Hi, I really want to attain creation date of mp4 file using pure javascript lib, and I hope this is right place for that. As I mentioned earlier, I have one sample mp4 file in my tmp web server, and I can get exif data using exiftool.

http://dev.qoontree.com:7001/sample-video.mp4
http://dev.qoontree.com:7001/metadata.txt

When I use your function, I got this.

{
  ftp: “isom”,
  type: “MP4”,
  version: 512,
  tags: {
    ©too: {
      data: “Lavf53.24.2”,
      description: “Encoding Tool”,
      id: “©too”,
      size: 35
    }
  }
}

But, in metadata.txt I can see the other infos like 'Modify Date: 2014:07:19 17:15:29'. Is there any chance to get creation or modify date info using your lib?

Is this right library to get exif data like creation date?

It will be great if you check this for me.

**Comment by aadsm** [comment]
The short answer is no.
This library is only concerned with the actual tag data. I don't have plans to include metadata of the file, I want to keep it as focused as possible.
This is also information that I wouldn't be able to obtain from all types of byte source, for instance, from a Blob.

**Comment by HongSeokHwan** [comment]
Thanks :)
