### ISSUE TITLE
Error: Cannot find module 'jsmediatags'

### ISSUE THREAD

**Issue by telpalbrox** [aadsm/jsmediatags#20]
When I require the module in node it fails.
It seems that you didn't upload the build2 folder to npm.
You can see it failing here: https://travis-ci.org/telpalbrox/MoonSongs/builds/127160239#L1299
```
tree node_modules/jsmediatags -a
node_modules/jsmediatags
├── .npmignore
├── LICENSE.md
├── README.md
└── package.json
```

**Comment by aadsm** [comment]
Thanks, I've just published the latest version.
