### ISSUE TITLE
Is it possible to consume the package using webpack?

### ISSUE THREAD

**Issue by sabbirrahman** [aadsm/jsmediatags#24]
I've installed jsmediatags from npm and then I tried to use like this:
`var jsmediatags = require("jsmediatags");`

Which gives me an error like this:
`./~/jsmediatags/build2/NodeFileReader.js Module not found: Error: Cannot resolve module 'fs'`
I guess this is the version to be used in the backed.

When I use the downloaded jsmediatags.js or jsmediatags.min.js likes this:
`var jsmediatags = require('./assets/js/jsmediatags');`

It works but I get this warning:
`./src/assets/js/jsmediatags.js
Critical dependencies: 1:484-491 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
@ ./src/assets/js/jsmediatags.js 1:484-491`

So my question is, Is it possible to require the front-end version directly from the npm directory? If not, it will be great if you add these dist files with the npm package or some other way so we can require the package directly from node_modules directory something like this:
`var jsmediatags = require('jsmediatags/dist/jsmediatags');`

**Comment by aadsm** [comment]
I'm not planning to add these files to the npm package but I've added bower support: https://github.com/aadsm/jsmediatags/issues/19.
It's also available in cdnjs: https://cdnjs.com/libraries/jsmediatags

**Comment by vyorkin** [comment]
@aadsm sorry, but I still don't understand how to use it in browser without "copying the dist/jsmediatags.min.js file"

**Comment by badbecario** [comment]
@vyorkin

Try to add this to you webpack config

node: {
  fs: "empty"
}

**Comment by vyorkin** [comment]
@badbecario thanks, this is was the first thing I've tried, but it doesn't help, unfortunately

**Comment by jasonh42** [comment]
@vyorkin - @badbecario's fix worked for me.

**Comment by vyorkin** [comment]
@jasonh42 @badbecario yeah, I've just tried one more time – it works, actually, but now I got this:
```
Unable to parse media tags for file 0.mp3:  ReferenceError: FileAPIReader is not defined(…)
```
not sure its related to this issue though

**Comment by vyorkin** [comment]
@jasonh42, @badbecario yeah, I've just tried one more time – it works, but now I got this:
```
Unable to parse media tags for file 03. Drift.mp3:  TypeError: fs.stat is not a function(…)
```
so even if I set `fs` to be `"empty"` it uses it anyway
