### ISSUE TITLE
Working with local mp3 files

### ISSUE THREAD

**Issue by pedrovelasquez9** [aadsm/jsmediatags#27]
Hi! I've been trying to load the tags of a local mp3 file on my Android device, I load de .js on my index:

<script src="lib/dist/jsmediatags.js"></script>

And, on my angular controller, I have this:
var jsmediatags = window.jsmediatags;
jsmediatags.read($scope.song, {
      	onSuccess: function(tag) {
                      	console.log(tag);
       	},
       onError: function(error) {
                      console.log(error);
	}
});

The $scope.song has the file's localURL. When I run it, the jsmediatags shows me this on the js console:

info: "Unexpected HTTP status 0."
type: "xhr"

Could you help me? I really need my local files tags. Thanks!

**Comment by aadsm** [comment]
I'm not familiar with loading local files from Android, what are you using, PhoneGap/Cordova?
If yes then follow this guide: http://www.raymondcamden.com/2015/04/30/working-with-mp3s-id3-and-phonegapcordova-2
