### ISSUE TITLE
`Object` in `mediaFileReaders` `Array` results in mediaFileReaders[i].canReadFile is not a function

### ISSUE THREAD

**Issue by vyorkin** [aadsm/jsmediatags#31]
I've got an empty `Object` in `mediaFileReaders` `Array`:

```
jsmediatags.js:2259 Uncaught TypeError: mediaFileReaders[i].canReadFile is not a function
_findFileReader @ jsmediatags.js:2259
_getFileReader @ jsmediatags.js:2252
read @ jsmediatags.js:2230
read @ jsmediatags.js:2199
(anonymous function) @ actions.ts:105
actions.ts:104 File
```

Using `webpack` + `babel-loader` without any plugins & presets.

**Comment by vyorkin** [comment]
https://www.dropbox.com/s/ru91wknjnm0p2c1/Screenshot%202016-07-06%2020.57.28.png?dl=0

**Comment by vyorkin** [comment]
I've changed it to be:
```
for (var i = 0; i < mediaFileReaders.length; i++) {
        var canReadFile = mediaFileReaders[i].canReadFile;
        if (typeof(canReadFile) === 'function' && canReadFile(this._file)) {
          return mediaFileReaders[i];
        }
      }
```
but now I'm getting: `jsmediatags.js:2265 Uncaught Error: No suitable file reader found for `,
this._file is a String and its equal to "test.mp3"

**Comment by aadsm** [comment]
Can you provide the music file that shows this error?

**Comment by vyorkin** [comment]
As I remember I was getting it for any/every file, e.g.
[test.mp3.zip](https://github.com/aadsm/jsmediatags/files/478274/test.mp3.zip)

**Comment by aadsm** [comment]
That's not an mp3 file, it's a wav actually. I looked into the file and didn't find any ID3 tags, maybe it's coded as RIFF tags? This library doesn't support RIFF tags at this point in time though.

**Comment by vyorkin** [comment]
yeah, sorry, I've forgotten to mention that
I use this tool https://github.com/sunny256/cwwav to generate wav files for testing purposes.

I mean, maybe it should fail with some error message that makes sense, e.g. `"<filetype> is not supported"` or smth like that

**Comment by NingerJohn** [comment]
I've got the same error while I use the following code to read tags from mp4 video
```
var jsmediatags = require("jsmediatags");
console.log(filedir)
jsmediatags.read(filedir, {
    onSuccess: function (tag) {
        console.log(tag);
    },
    onError: function (error) {
        console.log(':(', error.type, error.info);
    }
});
```
