### ISSUE TITLE
User defined URL link/text frames incorrectly parsed

### ISSUE THREAD

**Issue by singjsong** [aadsm/jsmediatags#38]
[User defined URL link frames](http://id3.org/id3v2.3.0#User_defined_URL_link_frame) are being incorrectly parsed. Code is assuming that the frame description value is the frame value, but the actual URL is actually right after the description. Results in output e.g.:
```
{
...
WXXX: { 
  id: 'WXXX',
  size: 83,
  description: 'User defined URL link frame',
  data: 'Description of the user defined link frame'
},
...
}
```

Haven't verified it, but am also positive that the same is happening for [user defined text frames](http://id3.org/id3v2.3.0#User_defined_text_information_frame) given that the code is very similar.

**Comment by aadsm** [comment]
Yeah, nice find. I don't have time right now to do this, the code is here: https://github.com/aadsm/jsmediatags/blob/master/src/ID3v2FrameReader.js#L130-L146
Do you want to try a PR for this?

**Comment by aadsm** [comment]
This has been fixed now, thank you for your PR!
