### ISSUE TITLE
NPM Distribution

### ISSUE THREAD

**Issue by toddpi314** [aadsm/jsmediatags#4]
Dist folder is missing from the NPM package @3.0.0

Missing the empty `.npmignore` file in the root of the project during npm pkgbuild?
You could also point your `package.json` to the dist build like this https://github.com/DeepElement/winjsrocks/blob/master/package.json#L22-L25

**Comment by toddpi314** [comment]
Note that the dist being packaged in important because the module is ES6. It would be better to package the transpiled code so we can include in pre-IO node

**Comment by aadsm** [comment]
Yeah, I ship the compiled code in `build/` not `dist/`: https://github.com/aadsm/jsmediatags/blob/master/package.json#L21 (https://github.com/aadsm/jsmediatags#nodejs-with-compiled-code-faster)
In `dist/` I put the browserified version.

Is this structure a problem?

**Comment by aadsm** [comment]
If this is still an issue please re-open.

**Comment by natecavanaugh** [comment]
@aadsm Just an FYI, but this is actually still an issue. The build directory isn't being included as part of the NPM distribution.
To test yourself, just try to install it locally from npm, and neither the src nor the build directory is included (meaning it's unusable in it's current state, unless you clone the git repo into your node_modules directory, and run `npm run build`, but I don't think it was your intention to require that process).

Just thought I'd share :)

**Comment by aadsm** [comment]
Thank you for bringing this up, the OP mentioned the `build` which is indeed not supposed to go in.
I've just published a new version with this fixed!

**Comment by toddpi314** [comment]
I was speculating on the name. Sorry for delay. Excellent lib by the way!

**Comment by aadsm** [comment]
@toddpi314 Ah! hehe, I should have checked though. Thank you for bringing this to my attention!
