### ISSUE TITLE
How to retrieve data from chapters?

### ISSUE THREAD

**Issue by hllwd** [aadsm/jsmediatags#42]
Hi!

First, thank you for the lib and the documentation, it was really helpful!
I'm trying to develop a browser side mp3 player (and to manage id3 v2.4.0 data to enhance the UX) but can't reach the data into chapters (we've provided pictures and titles):

```javascript
[{"id":"CHAP","size":51749,"description":"Unknown","data":null},{"id":"CHAP","size":46,"description":"Unknown","data":null},{"id":"CHAP","size":516417,"description":"Unknown","data":null},{"id":"CHAP","size":176998,"description":"Unknown","data":null},{"id":"CHAP","size":219066,"description":"Unknown","data":null},{"id":"CHAP","size":50,"description":"Unknown","data":null}]
```
My question is: is this a limitation of the lib or is there a way to reach these data? Maybe on overloading one of the MediaTagReader class?

(My repo is here: https://github.com/seracio/sound-player/blob/master/src/index.js)

**Comment by aadsm** [comment]
Chapters are not implemented yet. Here's the spec: http://id3.org/id3v2-chapters-1.0.
It could become a nice little feature for someone who wants to start working on open source projects.

**Comment by hllwd** [comment]
Haha, thanks! I'll give it a try!

**Comment by tom-sherman** [comment]
Currently taking a crack at this, @hllwd how far did you get?

**Comment by hllwd** [comment]
Hi @tom-sherman, sorry, I finally did not try at all :shame

**Comment by hllwd** [comment]
But let me know if you want some help or at least some test (I have a file with chapters here: https://github.com/seracio/sound-player/blob/master/data/testpodcastfigtech-v2.mp3)

**Comment by tom-sherman** [comment]
@hllwd no problem, thanks for the test file! I'll keep you updated

**Comment by aadsm** [comment]
The latest version, 2.6.0, has now support for Chapters thanks to @nils!!
