### ISSUE TITLE
iTunes m4a files: Strange format and missing tags

### ISSUE THREAD

**Issue by mrj** [aadsm/jsmediatags#44]
Does jsmediatags fully support iTunes music m4a files?

Below is an example output. Is this the expected format? Also, many tags found by exiftool are not in the output.

[iTunes jsmediatags Example.txt](https://github.com/aadsm/jsmediatags/files/746695/iTunes.jsmediatags.Example.txt)

If work needs to be done to support this, I'd appreciate some guidance on what needs to be done.

**Comment by aadsm** [comment]
It currently supports these: https://github.com/aadsm/jsmediatags/blob/master/src/MP4TagReader.js#L256-L299

But that is the expected format yes, it's a dictionary of tag name and respective content. To make this more friendly I created the concept of shortcuts that gives human readable names to tags. These are the ones supported for mp4: https://github.com/aadsm/jsmediatags/blob/a947d3c47ca3f3facfb423c6bc3dc0e78edcbd36/src/MP4TagReader.js#L305-L315 Feel free to add more and submit a PR, would gladly accept.

**Comment by mrj** [comment]
Thanks for reassuring me about the format. I had been expecting something like that shown in the README.md file.

Thanks also for pointing me to the correct section of your code. I've created PR #47.

**Comment by aadsm** [comment]
@mrj do you think the README.md could be improved on this? Happy to clarify things there.
