### ISSUE TITLE
Offset 110727 hasn't been loaded yet

### ISSUE THREAD

**Issue by robtoll** [aadsm/jsmediatags#49]
Hello! I've used jsmediatags successfully with many mp3 files, but some files don't return any tags.
The files contain ID3v1.1 and ID3v2.3.0 tags. The 2.3.0 has an embedded image 500px x 500px.
The tags are read successfully in Kid3, WinAmp, and on my Phone audio player.

The info attribute of the tag object says "Offset 110727 hasn't been loaded yet.".

I found this, but can't be sure it's the same issue...
[https://github.com/aadsm/jsmediatags/issues/14]

Many thanks.

Rob

**Comment by robtoll** [comment]
More info.

It varies on each track...
Object {type: "parseData", info: "Offset 110988 hasn't been loaded yet."}
Object {type: "parseData", info: "Offset 110727 hasn't been loaded yet."}
Object {type: "parseData", info: "Offset 112555 hasn't been loaded yet."}
Object {type: "parseData", info: "Offset 110904 hasn't been loaded yet."}

No idea what the issue is. Any help is well appreciated. It's a personal project - not commercial!

**Comment by aadsm** [comment]
Can you give me a file that triggers this error? Also, which version are you using?

**Comment by robtoll** [comment]
Hi. Thanks for the reply. For the version number, I'm really not sure! There are no version numbers in any of the code! I've abandoned my mp3 project because I couldn't find anything to handle the id3 tags reliably in javascript.

But for your reference, here's a file that wouldn't work with artwork or tags...

http://tolli.co.uk/Higgins_Tipper.zip

Thanks

**Comment by aadsm** [comment]
Hey @robtoll, thanks for the example, I found the bug and fixed it. It was an issue with the unsynchronisation support implementation.
This is now fixed on version 3.6.1.

**Comment by robtoll** [comment]
Excellent. Well done! I'll take a look
