### ISSUE TITLE
Reading Files tags

### ISSUE THREAD

**Issue by gurdilou** [aadsm/jsmediatags#5]
Hi,

I'm trying to use the package inside a phonegap application. I started from the previous version and followed the [Raymond Camden's article](http://www.raymondcamden.com/2015/04/30/working-with-mp3s-id3-and-phonegapcordova-2/).

I observed that the package doesn't work anymore with Files. In  [BlobFileReader]( ../blob/master/src/BlobFileReader.js), l.25, returns false for Files :

```javascript
static canReadFile(file: any): boolean {
    return (
      typeof Blob !== "undefined" &&
      file instanceof Blob
    );
  }
```

Shouldn't be changed to something like ?
``` javascript
return ((typeof Blob !== "undefined") && ( (file instanceof Blob) ||(file instanceof File) ));
```

Thanks !

**Comment by aadsm** [comment]
Interesting, `File` is a subclass of `Blob`, so `instanceof Blob` should be enough, you can see it in this demo: http://codepen.io/anon/pen/ZQMarw?editors=1011
Can you try adding the `instanceof File` in your local copy to make sure it works under Cordova?

**Comment by gurdilou** [comment]
Yup, maybe it's more a corodova issue.. When logging at the execution with :
``` javascript
    value: function canReadFile(file) {
      console.log("(file instanceof Blob) : "+(file instanceof Blob));
      console.log("(file instanceof File) : "+(file instanceof File));
      return (typeof Blob !== "undefined") && ( (file instanceof Blob) ||(file instanceof File) );
    }
```
It outputs :

```
(file instanceof Blob) : false    jsmediatags.js:79
(file instanceof File) : true      jsmediatags.js:79
```
