### ISSUE TITLE
Add browser version to npm

### ISSUE THREAD

**Issue by Luucky** [aadsm/jsmediatags#52]
Hello, I'm wondering why the dist folder is not included in npm package. I am using npm to manage my browser application and to keep it updated.. Can you please include the dist folder in npm package to make it easier for developers. Thanks in advance.

Regards,
Mike

**Comment by aadsm** [comment]
Hi @Luucky, the reason I don't to that is to prevent doubling the size of the npm package. Package size is a common complain among npm users.
Maybe I can create a separate npm package just for the web?

**Comment by icidasset** [comment]
Would like a separate npm package for this as well 👍

**Comment by aadsm** [comment]
I've just published version 3.5.0 with the `dist` directory, since it was only ~200KB I just added it. Can you reopen this if it's not enough?
