### ISSUE TITLE
Getting this to work

### ISSUE THREAD

**Issue by KensonN** [aadsm/jsmediatags#54]
I'm relatively new to JavaScript, so please excuse any errors I make in my explanation. So, I am trying to use the browser version of this, but I can't get the example code to work. Is anyone able to help a beginner out?

**Comment by aadsm** [comment]
Sure, can you explain what you did? You can also use https://jsfiddle.net/ to show what you did.

**Comment by KensonN** [comment]
Hi. Thanks for the response! I am trying to read the metadata of local files using the browser version of the library. Are you able to guide me through this?

**Comment by aadsm** [comment]
The browser version can only read files served through HTTP, it's not able to access the local filesystem.
