### ISSUE TITLE
how to use picture.data?

### ISSUE THREAD

**Issue by doubear** [aadsm/jsmediatags#59]
i'm trying to show it by the code:

`
URL.createObjectURL(new Blob(tag.tags.picture.data, {
    type: tag.tags.picture.format
}))
`

but fail, how to use it?

**Comment by aadsm** [comment]
The first argument to the Blob constructor needs to be `an Array of ArrayBuffer, ArrayBufferView, Blob, DOMString` which is not the case for `.picture.data`.
I do it like this in my code:

```javascript
var imageData = frame.data.data;
var base64String = "";
for (var i = 0; i < imageData.length; i++) {
  base64String += String.fromCharCode(imageData[i]);
}
content = document.createElement("img");
content.src = "data:" + frame.data.format + ";base64," + window.btoa(base64String);
```

**Comment by feedgit** [comment]
@captbaritone Thanks bro!

**Comment by aadsm** [comment]
@captbaritone yes! would love to have it :)

**Comment by Borewit** [comment]
As commented in my review on #112 

I don't think you want to use `picture.type`:
https://github.com/aadsm/jsmediatags/blob/2f52390c2882a3bc005f2f356a6e6cf99bb93045/src/ID3v2FrameReader.js#L687-L709

I had more luck using:

```js
// picture.format using music-metadata this is a valid MIME type, not sure if that is the case here
img.src = `data:${picture.format};base64,${picture.data.toString('base64')}`;
```

**Comment by mohamed-ayman-aly** [comment]
const base64String = tags.tags.picture.data.map(ch => String.fromCharCode(ch)).join(''); 
it is much faster
