### ISSUE TITLE
Please babelify the build2 directory

### ISSUE THREAD

**Issue by C-Higgins** [aadsm/jsmediatags#60]
I cannot use this package with Uglify as the files in build2 are still ES6.

**Comment by aadsm** [comment]
Not sure what you mean with "babelify", can you provide more context? `build2/` is the output of running babel through the source code: https://github.com/aadsm/jsmediatags/blob/master/package.json#L58.

This directory is also meant to be used by node which supports ES6, if you want to use the browser version check `dist/`.

**Comment by C-Higgins** [comment]
What I mean is that it would be convenient to have these files already compiled into ES5, for use in build configurations like Webpack where these files are used on the front end. I'm sure many would prefer not to include the dist min file because it doesn't auto update on builds and etc. I've already compiled it myself, just something to consider

**Comment by aadsm** [comment]
What do you mean that the dist min file doesn't auto update on builds? These files should be available on all releases.
