### ISSUE TITLE
XHR InvalidStateError in IE

### ISSUE THREAD

**Issue by JaguarWeb** [aadsm/jsmediatags#63]
XHR InvalidStateError in IE.

Can be fixed by moving

xhr.open(method, this._url);

and place it after

var xhr = this._createXHRObject();

**Comment by aadsm** [comment]
Which version of IE? I haven't tested on IE for a while.

**Comment by JaguarWeb** [comment]
Not IE, in Old Firefox, this is a bug in XHR implementatios. Very known.

If you want to set anything, such as `timeout` or `responseType`, you must open before you set, otherwise exception is thrown if the state is not `OPENED` or `HEADERS_RECEIVED`.
