### ISSUE TITLE
Offset <..> hasn't been loaded yet.

### ISSUE THREAD

**Issue by pioug** [aadsm/jsmediatags#69]
```js
{ type: 'parseData',
  info: 'Offset 70666 hasn\'t been loaded yet.' }
```
I am facing this issue with few files. I am using `3.6.2`. I pushed a test case here: https://github.com/aadsm/jsmediatags/compare/master...pioug:issue?expand=1.

I saw that you fixed similar errors recently with different solutions (https://github.com/aadsm/jsmediatags/issues/58, https://github.com/aadsm/jsmediatags/issues/49). So I am better asking you first before digging in the code 🤔

**Comment by aadsm** [comment]
@pioug, the link you provide doesn't point me to the test case, can you update it so I can have access to the music file and fix the issue?

**Comment by pioug** [comment]
I just realized that the parsing works well in the browser but not in Node. It may be easier to solve than I thought.

What is the easiest solution to provide you a test case for Node? So far, I forked your project https://github.com/pioug/jsmediatags/tree/master and added the test files in `/issue`. You can run the script via `node issue/`.

Link to browser version: https://pioug.github.io/jsmediatags/issue/index.html.

Thanks a lot for the weekend support!

**Comment by aadsm** [comment]
This is an interesting case, it looks like cry.mp3 has a 2 byte padding at the end of the tag but it doesn't have an extended header declaring padding size.
I'll add a sanity check to detect this issue.

**Comment by pioug** [comment]
Awesome support! It works perfectly now. `jsmediatags` parses my +30 GB library without flinching 😛 Thanks a lot!
