### ISSUE TITLE
get audio file duration

### ISSUE THREAD

**Issue by maicss** [aadsm/jsmediatags#70]
Is there a method to get an audio file duration?

**Comment by aadsm** [comment]
You can read this information from the TLE or TLEN tag if it's available on the metadata of the file for MP3s.
This library only reads metadata and doesn't process any of the audio content. This is has been discussed to a certain extended here aadsm/JavaScript-ID3-Reader/issues/5.

**Comment by maicss** [comment]
OK, thanks.
