### ISSUE TITLE
Offset 0 hasn't been loaded yet

### ISSUE THREAD

**Issue by blatter2016** [aadsm/jsmediatags#80]
Hi,

Correct me if I'm wrong, but it seems like the fix to this issue was fixed/merged in master, but it doesn't reflect in the dist yet. https://github.com/aadsm/jsmediatags/blob/a11c88865dfa03beffb181129b6c3489ccba9f1e/dist/jsmediatags.js#L106

Thanks for this awesome library!

**Comment by aadsm** [comment]
Nice catch, not sure why tbh. The npm version should be fine though, since I always recompile before publishing.

**Comment by qnstie** [comment]
The fix is still not reflected in the dist.

**Comment by aadsm** [comment]
I just release `3.8.2` that should fix this.
