### ISSUE TITLE
parseData Offset 1025 hasn't been loaded yet.

### ISSUE THREAD

**Issue by Torannach** [aadsm/jsmediatags#81]
I'm using jsmediatags in an Angular4 application by importing it like so 
`import * as jsmediatags from 'jsmediatags'`

I have a simple function that runs inside ngOnInit()

`jsmediatags.read("https://s3.amazonaws.com/jsmediatags-offset-issue/audio.mp3", {
      onSuccess: function(tags) {
        console.log(tags.tags.title);
      },
      onError: function(error) {
        console.log(error);
      }
    });`

However, I keep getting the parseData Offset 1025 hasn't been loaded yet. error.

It works fine on local files

**Comment by aadsm** [comment]
I’m able to run that without any problem on the current version, you can check it here: https://runkit.com/embed/wbxb5fc12xwl
