### ISSUE TITLE
Getting song duration

### ISSUE THREAD

**Issue by ithustle** [aadsm/jsmediatags#95]
Hi,

Is there a way to get a song duration?

Thanks

CG

**Comment by captbaritone** [comment]
I have a similar need. I ended up doing this: https://github.com/captbaritone/webamp/blob/master/js/fileUtils.js#L34

It requires a separate request (and that you are running in the browser) so it’s far from ideal, but it works okay.

**Comment by ithustle** [comment]
Hi @captbaritone 
Nice one.

Thanks
